foreach(_required TOOL DOWNSTREAM_TOOL EXTERNAL_CONSUMER MANIFEST_DIR WORK_DIR)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "${_required} is required")
    endif()
endforeach()

file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")

function(run_ok)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Command failed (${_result}): ${ARGN}\nstdout: ${_output}\nstderr: ${_error}")
    endif()
    set(LAST_OUTPUT "${_output}" PARENT_SCOPE)
endfunction()

run_ok("${TOOL}" list)
string(JSON _count LENGTH "${LAST_OUTPUT}" schemas)
set(_resource_count 0)
math(EXPR _last "${_count} - 1")
foreach(_index RANGE 0 ${_last})
    string(JSON _kind GET "${LAST_OUTPUT}" schemas ${_index} kind)
    if(_kind STREQUAL "resourceType")
        math(EXPR _resource_count "${_resource_count} + 1")
    endif()
endforeach()
if(NOT _resource_count EQUAL 9)
    message(FATAL_ERROR "Built-in CLI list returned ${_resource_count}, not nine, Resource Types")
endif()

run_ok("${TOOL}" export --output "${WORK_DIR}/first")
run_ok("${TOOL}" export --output "${WORK_DIR}/second")
file(SHA256 "${WORK_DIR}/first/catalog.json" _first_catalog)
file(SHA256 "${WORK_DIR}/second/catalog.json" _second_catalog)
file(SHA256 "${WORK_DIR}/first/resource-manifest.schema.json" _first_root)
file(SHA256 "${WORK_DIR}/second/resource-manifest.schema.json" _second_root)
if(NOT _first_catalog STREQUAL _second_catalog OR NOT _first_root STREQUAL _second_root)
    message(FATAL_ERROR "Identical CLI inputs did not produce byte-for-byte stable output")
endif()

run_ok("${DOWNSTREAM_TOOL}" merge --output "${WORK_DIR}/merged"
       --root-schema-id "https://schemas.example.test/merged-resource-manifest.schema.json")
file(READ "${WORK_DIR}/merged/catalog.json" _merged_catalog)
if(NOT _merged_catalog MATCHES "Widget" OR NOT _merged_catalog MATCHES "merged-resource-manifest")
    message(FATAL_ERROR "CLI merge did not compose the downstream catalog")
endif()

run_ok("${DOWNSTREAM_TOOL}" export --output "${WORK_DIR}/downstream"
       --root-schema-id "https://schemas.example.test/cli-resource-manifest.schema.json")
file(READ "${WORK_DIR}/downstream/catalog.json" _catalog)
file(READ "${WORK_DIR}/downstream/resource-manifest.schema.json" _root)
if(NOT _catalog MATCHES "Widget" OR NOT _root MATCHES "Widget" OR NOT _root MATCHES "GlowFactory")
    message(FATAL_ERROR "Downstream exporter output does not contain its registered Resource Types")
endif()
foreach(_case valid-mixed invalid-default invalid-specialized)
    execute_process(
        COMMAND "${EXTERNAL_CONSUMER}" "${WORK_DIR}/downstream" "${MANIFEST_DIR}/${_case}.yaml"
        RESULT_VARIABLE _validation_result)
    if(_case STREQUAL "valid-mixed")
        set(_expected 0)
    else()
        set(_expected 1)
    endif()
    if(NOT _validation_result EQUAL _expected)
        message(FATAL_ERROR
            "CLI-exported bundle returned ${_validation_result} for ${_case}, expected ${_expected}")
    endif()
endforeach()

file(COPY "${WORK_DIR}/first/" DESTINATION "${WORK_DIR}/invalid")
file(READ "${WORK_DIR}/invalid/catalog.json" _invalid_catalog)
string(FIND "${_invalid_catalog}" "sha256:" _hash)
math(EXPR _digit "${_hash} + 7")
string(SUBSTRING "${_invalid_catalog}" ${_digit} 1 _old_digit)
if(_old_digit STREQUAL "0")
    set(_new_digit "1")
else()
    set(_new_digit "0")
endif()
string(SUBSTRING "${_invalid_catalog}" 0 ${_digit} _before)
math(EXPR _after_at "${_digit} + 1")
string(SUBSTRING "${_invalid_catalog}" ${_after_at} -1 _after)
file(WRITE "${WORK_DIR}/invalid/catalog.json" "${_before}${_new_digit}${_after}")
execute_process(COMMAND "${TOOL}" verify --bundle "${WORK_DIR}/invalid"
                RESULT_VARIABLE _invalid_result OUTPUT_VARIABLE _invalid_out ERROR_VARIABLE _diagnostic)
if(_invalid_result EQUAL 0)
    message(FATAL_ERROR "Hash-corrupt input unexpectedly verified")
endif()
string(JSON _ok GET "${_diagnostic}" ok)
string(JSON _bundle GET "${_diagnostic}" bundle)
string(JSON _message GET "${_diagnostic}" message)
if(_ok OR NOT _bundle MATCHES "invalid" OR NOT _message MATCHES "hash mismatch")
    message(FATAL_ERROR "Invalid input diagnostic is not machine readable/actionable: ${_diagnostic}")
endif()
