# Generates a deterministic Resource Schema Bundle from canonical JSON Schema files.
#
# RECORDS entries are:
#   kind|resource-type|factory-type|schema-id|document-name|absolute-source-path
# kind is one of dependency, manifest, or resourceType. An empty factory type denotes
# the default factory. Resource and factory types are empty for non-resource entries.
cmake_policy(VERSION 3.25)

if(DEFINED RECORDS_FILE)
    include("${RECORDS_FILE}")
endif()
if(NOT DEFINED OUTPUT_DIR OR NOT DEFINED RECORDS)
    message(FATAL_ERROR "OUTPUT_DIR and RECORDS (or RECORDS_FILE) are required")
endif()

function(_wp_validate_json_pointer JSON FRAGMENT CONTEXT)
    if(FRAGMENT STREQUAL "")
        return()
    endif()
    if(NOT FRAGMENT MATCHES "^/")
        message(FATAL_ERROR "Unsupported or unresolved JSON Schema fragment '#${FRAGMENT}' in ${CONTEXT}")
    endif()
    string(SUBSTRING "${FRAGMENT}" 1 -1 _pointer)
    string(REPLACE "/" ";" _segments "${_pointer}")
    set(_decoded_segments "")
    foreach(_segment IN LISTS _segments)
        string(REPLACE "~1" "/" _segment "${_segment}")
        string(REPLACE "~0" "~" _segment "${_segment}")
        list(APPEND _decoded_segments "${_segment}")
    endforeach()
    string(JSON _pointed_value ERROR_VARIABLE _pointer_error GET "${JSON}" ${_decoded_segments})
    if(_pointer_error)
        message(FATAL_ERROR "Unresolved JSON Schema reference '#${FRAGMENT}' in ${CONTEXT}: ${_pointer_error}")
    endif()
endfunction()

list(SORT RECORDS)
set(_record_count 0)
set(_keys "")
set(_schema_ids "")
set(_schema_hashes "")
set(_schema_id_record_indices "")
set(_document_names "")
set(_document_hashes "")

# Validate and index every catalog entry before resolving references.
foreach(_record IN LISTS RECORDS)
    string(REPLACE "|" ";" _fields "${_record}")
    list(LENGTH _fields _field_count)
    if(NOT _field_count EQUAL 6)
        message(FATAL_ERROR "Invalid Resource Schema Bundle record: ${_record}")
    endif()
    list(GET _fields 0 _kind)
    list(GET _fields 1 _resource_type)
    list(GET _fields 2 _factory_type)
    list(GET _fields 3 _declared_schema_id)
    list(GET _fields 4 _document_name)
    list(GET _fields 5 _source_path)

    if(NOT _kind MATCHES "^(dependency|manifest|resourceType)$")
        message(FATAL_ERROR "Invalid bundle entry kind '${_kind}'")
    endif()
    if(_kind STREQUAL "resourceType")
        if(_resource_type STREQUAL "")
            message(FATAL_ERROR "A resourceType entry must have a Resource Type")
        endif()
        set(_key "${_resource_type}|${_factory_type}")
        if(_key IN_LIST _keys)
            message(FATAL_ERROR "Duplicate Resource Schema Bundle key (${_resource_type}, ${_factory_type})")
        endif()
        list(APPEND _keys "${_key}")
    elseif(NOT _resource_type STREQUAL "" OR NOT _factory_type STREQUAL "")
        message(FATAL_ERROR "${_kind} entries cannot have Resource or factory types")
    endif()
    if(_document_name STREQUAL "" OR _document_name MATCHES "(^|/)\.\.(/|$)" OR
       _document_name MATCHES "^/" OR _document_name MATCHES "[\\\\:]")
        message(FATAL_ERROR "Unsafe bundle document name '${_document_name}'")
    endif()
    if(NOT EXISTS "${_source_path}" OR IS_DIRECTORY "${_source_path}")
        message(FATAL_ERROR "Missing or non-regular schema document: ${_source_path}")
    endif()

    file(READ "${_source_path}" _schema_json)
    string(JSON _actual_schema_id ERROR_VARIABLE _id_error GET "${_schema_json}" "$id")
    if(_id_error OR _actual_schema_id STREQUAL "")
        message(FATAL_ERROR "Schema document ${_source_path} has no valid $id")
    endif()
    if(NOT _actual_schema_id STREQUAL _declared_schema_id)
        message(FATAL_ERROR "Schema ID mismatch for ${_source_path}: expected '${_declared_schema_id}', found '${_actual_schema_id}'")
    endif()
    file(SHA256 "${_source_path}" _document_hash)
    list(FIND _document_names "${_document_name}" _existing_document_index)
    if(NOT _existing_document_index EQUAL -1)
        list(GET _document_hashes ${_existing_document_index} _existing_document_hash)
        if(NOT _existing_document_hash STREQUAL _document_hash)
            message(FATAL_ERROR "Bundle document '${_document_name}' has different source content")
        endif()
    else()
        list(APPEND _document_names "${_document_name}")
        list(APPEND _document_hashes "${_document_hash}")
    endif()

    list(FIND _schema_ids "${_actual_schema_id}" _existing_id_index)
    if(NOT _existing_id_index EQUAL -1)
        list(GET _schema_hashes ${_existing_id_index} _existing_hash)
        if(NOT _existing_hash STREQUAL _document_hash)
            message(FATAL_ERROR "Duplicate schema ID '${_actual_schema_id}' has different content")
        endif()
    else()
        list(APPEND _schema_ids "${_actual_schema_id}")
        list(APPEND _schema_hashes "${_document_hash}")
        list(APPEND _schema_id_record_indices "${_record_count}")
    endif()

    set(_schema_json_${_record_count} "${_schema_json}")
    set(_schema_id_${_record_count} "${_actual_schema_id}")
    set(_source_path_${_record_count} "${_source_path}")
    set(_document_path_${_record_count} "schemas/${_document_name}")
    set(_hash_${_record_count} "${_document_hash}")
    set(_kind_${_record_count} "${_kind}")
    set(_resource_type_${_record_count} "${_resource_type}")
    set(_factory_type_${_record_count} "${_factory_type}")
    math(EXPR _record_count "${_record_count} + 1")
endforeach()

# Resolve every non-meta-schema $ref exclusively against documents in this bundle.
math(EXPR _last_record "${_record_count} - 1")
foreach(_index RANGE 0 ${_last_record})
    set(_schema_json "${_schema_json_${_index}}")
    string(REGEX MATCHALL "\"\\$ref\"[ \t\r\n]*:[ \t\r\n]*\"[^\"]+\"" _ref_members "${_schema_json}")
    foreach(_member IN LISTS _ref_members)
        string(REGEX REPLACE "^.*:[ \t\r\n]*\"([^\"]+)\"$" "\\1" _ref "${_member}")
        if(_ref MATCHES "^#(.*)$")
            _wp_validate_json_pointer("${_schema_json}" "${CMAKE_MATCH_1}" "${_source_path_${_index}}")
        else()
            string(REGEX REPLACE "#.*$" "" _target_id "${_ref}")
            string(REGEX MATCH "#(.*)$" _fragment_match "${_ref}")
            set(_fragment "${CMAKE_MATCH_1}")
            list(FIND _schema_ids "${_target_id}" _target_index)
            if(_target_index EQUAL -1)
                message(FATAL_ERROR "Unresolved local JSON Schema reference '${_ref}' in ${_source_path_${_index}}")
            endif()
            list(GET _schema_id_record_indices ${_target_index} _target_record_index)
            _wp_validate_json_pointer("${_schema_json_${_target_record_index}}" "${_fragment}" "${_source_path_${_index}}")
        endif()
    endforeach()
endforeach()

# Removing the old directory prevents deleted inputs from surviving as stale,
# history-dependent bundle content.
file(REMOVE_RECURSE "${OUTPUT_DIR}")
file(MAKE_DIRECTORY "${OUTPUT_DIR}/schemas")
set(_catalog "{\n  \"bundleFormatVersion\": \"1.0\",\n  \"resourceManifestSchemaVersion\": \"1.0\",\n  \"schemas\": [\n")
set(_separator "")
foreach(_index RANGE 0 ${_last_record})
    if(_resource_type_${_index} STREQUAL "")
        set(_resource_json "null")
    else()
        set(_resource_json "\"${_resource_type_${_index}}\"")
    endif()
    if(_factory_type_${_index} STREQUAL "")
        set(_factory_json "null")
    else()
        set(_factory_json "\"${_factory_type_${_index}}\"")
    endif()
    string(APPEND _catalog "${_separator}    {\n"
        "      \"kind\": \"${_kind_${_index}}\",\n"
        "      \"resourceType\": ${_resource_json},\n"
        "      \"factoryType\": ${_factory_json},\n"
        "      \"schemaId\": \"${_schema_id_${_index}}\",\n"
        "      \"document\": \"${_document_path_${_index}}\",\n"
        "      \"documentHash\": \"sha256:${_hash_${_index}}\"\n"
        "    }")
    set(_separator ",\n")
    file(COPY_FILE "${_source_path_${_index}}" "${OUTPUT_DIR}/${_document_path_${_index}}" ONLY_IF_DIFFERENT)
endforeach()
string(APPEND _catalog "\n  ]\n}\n")
file(WRITE "${OUTPUT_DIR}/catalog.json" "${_catalog}")
if(DEFINED OUTPUT_STAMP)
    file(WRITE "${OUTPUT_STAMP}" "Resource Schema Bundle 1.0\n")
endif()
