cmake_policy(VERSION 3.25)
if(NOT DEFINED BUNDLE_DIR OR NOT DEFINED GENERATOR OR NOT DEFINED RECORDS_FILE OR
   NOT DEFINED REGENERATED_DIR)
    message(FATAL_ERROR "BUNDLE_DIR, GENERATOR, RECORDS_FILE, and REGENERATED_DIR are required")
endif()
include("${RECORDS_FILE}")

file(READ "${BUNDLE_DIR}/catalog.json" _catalog)
string(JSON _format GET "${_catalog}" bundleFormatVersion)
string(JSON _manifest_version GET "${_catalog}" resourceManifestSchemaVersion)
if(NOT _format STREQUAL "1.0" OR NOT _manifest_version STREQUAL "1.0")
    message(FATAL_ERROR "Unexpected Resource Schema Bundle versions")
endif()
string(JSON _entry_count LENGTH "${_catalog}" schemas)
if(NOT _entry_count EQUAL 12)
    message(FATAL_ERROR "Built-in bundle must contain 12 catalog entries, found ${_entry_count}")
endif()

set(_resource_types "")
math(EXPR _last_entry "${_entry_count} - 1")
foreach(_index RANGE 0 ${_last_entry})
    string(JSON _kind GET "${_catalog}" schemas ${_index} kind)
    string(JSON _schema_id GET "${_catalog}" schemas ${_index} schemaId)
    string(JSON _document GET "${_catalog}" schemas ${_index} document)
    string(JSON _catalog_hash GET "${_catalog}" schemas ${_index} documentHash)
    if(NOT _catalog_hash MATCHES "^sha256:[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]$")
        message(FATAL_ERROR "Invalid SHA-256 in catalog entry ${_index}: ${_catalog_hash}")
    endif()
    if(NOT EXISTS "${BUNDLE_DIR}/${_document}")
        message(FATAL_ERROR "Catalog document is missing: ${_document}")
    endif()
    file(SHA256 "${BUNDLE_DIR}/${_document}" _actual_hash)
    if(NOT _catalog_hash STREQUAL "sha256:${_actual_hash}")
        message(FATAL_ERROR "Catalog hash mismatch for ${_document}")
    endif()
    file(READ "${BUNDLE_DIR}/${_document}" _schema)
    string(JSON _document_id GET "${_schema}" "$id")
    if(NOT _schema_id STREQUAL _document_id)
        message(FATAL_ERROR "Catalog schema ID mismatch for ${_document}")
    endif()
    if(_kind STREQUAL "resourceType")
        string(JSON _resource_type GET "${_catalog}" schemas ${_index} resourceType)
        list(APPEND _resource_types "${_resource_type}")
    endif()
endforeach()
list(SORT _resource_types)
set(_expected_types AnimationSet AudioBank Image ImageSet Material Program Shader TextFile XmlFile)
if(NOT _resource_types STREQUAL _expected_types)
    message(FATAL_ERROR "Unexpected built-in Resource Types: ${_resource_types}")
endif()

# Generate independently and compare every output byte (represented by SHA-256).
file(REMOVE_RECURSE "${REGENERATED_DIR}")
set(OUTPUT_DIR "${REGENERATED_DIR}")
unset(OUTPUT_STAMP)
include("${GENERATOR}")
file(GLOB_RECURSE _original_files RELATIVE "${BUNDLE_DIR}" "${BUNDLE_DIR}/*")
file(GLOB_RECURSE _regenerated_files RELATIVE "${REGENERATED_DIR}" "${REGENERATED_DIR}/*")
list(REMOVE_ITEM _original_files generated.stamp)
if(NOT _original_files STREQUAL _regenerated_files)
    message(FATAL_ERROR "Repeated generation produced a different file set")
endif()
foreach(_file IN LISTS _original_files)
    file(SHA256 "${BUNDLE_DIR}/${_file}" _original_hash)
    file(SHA256 "${REGENERATED_DIR}/${_file}" _regenerated_hash)
    if(NOT _original_hash STREQUAL _regenerated_hash)
        message(FATAL_ERROR "Repeated generation changed ${_file}")
    endif()
endforeach()
